# Generated by Django 2.0.4 on 2020-03-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
