# Generated by Django 2.0.4 on 2020-03-07 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_accept_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
